services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /mnt/worker/library
        target: /media
    restart: "unless-stopped"
