services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.ansango.com"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 8084:80
