services:
  strawberry:
    build: .
    container_name: strawberry
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - CUSTOM_USER=admin
      - PASSWORD=admin
    volumes:
      - ./config:/config
      - ~/Music:/music
    ports:
      - 1234:3000
      - 3001:3001
    restart: unless-stopped
